# Generated by Django 6.0.7 on 2026-07-09 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('numero_identidad', models.CharField(max_length=20, verbose_name='Cédula o ID')),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100)),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Propietario')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'db_table': 'propietario',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('estado', models.CharField(default='Autorizado', max_length=50)),
                ('id_propietario', models.ForeignKey(db_column='id_propietario', on_delete=django.db.models.deletion.CASCADE, to='vehiculos.propietario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
            },
        ),
    ]
