# Generated by Django 6.0.7 on 2026-07-09 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoValidacionEnum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Resultado de Validación',
                'verbose_name_plural': 'Resultados de Validación',
                'db_table': 'resultado_validacion_enum',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimientoEnum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Movimiento')),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimiento',
                'db_table': 'tipo_movimiento_enum',
            },
        ),
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id_codigo_qr', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(verbose_name='Contenido Encriptado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_expiracion', models.DateField(verbose_name='Fecha de Expiración')),
                ('activo', models.BooleanField(default=True, verbose_name='QR Activo')),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'db_table': 'codigo_qr',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionQR',
            fields=[
                ('id_configuracion_qr', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_renovacion', models.IntegerField(verbose_name='Tiempo de Renovación')),
                ('unidad_tiempo', models.CharField(max_length=20, verbose_name='Unidad de Tiempo (Ej. Horas, Días)')),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('id_administrador', models.ForeignKey(db_column='id_administrador', on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrador')),
            ],
            options={
                'verbose_name': 'Configuración de QR',
                'verbose_name_plural': 'Configuraciones de QR',
                'db_table': 'configuracion_qr',
            },
        ),
        migrations.CreateModel(
            name='RegistroMovimiento',
            fields=[
                ('id_registro_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('id_personal_seguridad', models.ForeignKey(db_column='id_personal_seguridad', on_delete=django.db.models.deletion.CASCADE, to='usuarios.personalseguridad')),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
                ('id_resultado_validacion', models.ForeignKey(db_column='id_resultado_validacion', on_delete=django.db.models.deletion.PROTECT, to='control_acceso.resultadovalidacionenum')),
                ('id_tipo_movimiento', models.ForeignKey(db_column='id_tipo_movimiento', on_delete=django.db.models.deletion.PROTECT, to='control_acceso.tipomovimientoenum')),
            ],
            options={
                'verbose_name': 'Registro de Movimiento',
                'verbose_name_plural': 'Registros de Movimientos',
                'db_table': 'registro_movimiento',
            },
        ),
    ]
